[build]
  command = """
    curl -fsSL https://bun.sh/install | bash \
    && export PATH=$HOME/.bun/bin:$PATH \
    && bun install \
    && BUN_BUILD_NO_TYPECHECK=1 bun build
  """
  publish = "build"
